main: me.notom3ga.ezcrash.EZCrash
name: EZCrash
version: 1.1
author: notOM3GA
api-version: 1.13
depend:
  - ProtocolLib

permissions:
  ezcrash.command:
    default: op
    description: Allows you to use the /crash command
commands:
  crash:
    permission: ezcrash.command
    description: Allows you to crash a client
    usage: /crash <player>
